// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":return img`
....66666666....
....66666666....
....76666667....
....d66666bd....
.....66666b.....
.....6666bc.....
.....666ccc.....
.....888888.....
.....888888.....
.....88..88.....
.....88..88.....
.....88..88.....
................
................
................
................
................
................
................
................
`;
            case "image2":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . c c c c c . . . . . 
. . . . c c c c c c c c . . . . 
. . . c c d d d d d d c . . . . 
. . c c d d d d d d d c . . . . 
. c c c d d f d d d f c . . . . 
. c c c d d d d d d d c c . . . 
. c c c c d d d d d d c c . . . 
. . . . . . . d d . . . . . . . 
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
